const axieCards = {
  cards: [
    {
      name: "Shelter",
      alias: "Hermit",
      energy: "1",
      attack: "0",
      defense: "115",
      description: "Disable critical strikes on this Axie during this round.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-02.png",
    },
    {
      name: "Scale Dart",
      alias: "Blue Moon",
      energy: "1",
      attack: "120",
      defense: "30",
      description: "Draw a card if target is in Last Stand.",
      attackType: "Ranged",
      class: "Aquatic",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-04.png",
    },
    {
      name: "Swift Escape",
      alias: "Goldfish",
      energy: "1",
      attack: "105",
      defense: "20",
      description: "Apply Speed+ to this Axie for 2 rounds when attacked.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-06.png",
    },
    {
      name: "Shipwreck",
      alias: "Sponge",
      energy: "1",
      attack: "60",
      defense: "90",
      description: "Apply Attack+ to this Axie if its shield breaks.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-08.png",
    },
    {
      name: "Aqua Vitality",
      alias: "Anemone",
      energy: "1",
      attack: "80",
      defense: "35",
      description:
        "Successful attacks restore 50 HP for each Anemone part this Axie posseses.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-10.png",
    },
    {
      name: "Spinal Tap",
      alias: "Perch",
      energy: "1",
      attack: "100",
      defense: "20",
      description:
        "Prioritize idle target when comboed with at least 2 additional cards.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-12.png",
    },
    {
      name: "Shell Jab",
      alias: "Babylonia",
      energy: "1",
      attack: "100",
      defense: "50",
      description: "Deal 130% damage when attacking an idle target.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-02.png",
    },
    {
      name: "Deep Sea Gore",
      alias: "Teal Shell",
      energy: "1",
      attack: "50",
      defense: "80",
      description: "Add 30% to this Axie's shield when attacking.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-04.png",
    },
    {
      name: "Clam Slash",
      alias: "Clamshell",
      energy: "1",
      attack: "110",
      defense: "40",
      description:
        "Apply Attack+ to this Axie when attacking Beast, Bug, or Mech targets.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-06.png",
    },
    {
      name: "Aquaponics",
      alias: "Anemone",
      energy: "1",
      attack: "80",
      defense: "35",
      description:
        "Successful attacks restore 50 HP for each Anemone part this Axie posseses.",
      attackType: "Ranged",
      class: "Aquatic",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-08.png",
    },
    {
      name: "Hero's Bane",
      alias: "Oranda",
      energy: "1",
      attack: "120",
      defense: "30",
      description: "End target's Last Stand.",
      attackType: "Ranged",
      class: "Aquatic",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-10.png",
    },
    {
      name: "Star Shuriken",
      alias: "Shoal Start",
      energy: "1",
      attack: "110",
      defense: "10",
      description:
        "Target cannot enter Last Stand if this card brings its HP to zero.",
      attackType: "Ranged",
      class: "Aquatic",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-12.png",
    },
    {
      name: "Angry Lam",
      alias: "Lam",
      energy: "1",
      attack: "110",
      defense: "40",
      description: "Deal 120% damage if this Axie's HP is below 50%.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-mouth-02.png",
    },
    {
      name: "Swallow",
      alias: "Catfish",
      energy: "1",
      attack: "80",
      defense: "30",
      description: "Heal this Axie by the damage inflicted with this card.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-mouth-04.png",
    },
    {
      name: "Fish Hook",
      alias: "Risky Fish",
      energy: "1",
      attack: "105",
      defense: "20",
      description:
        "Apply Attack+ to this Axie when attacking Plant, Reptile, or Dusk targets.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-mouth-08.png",
    },
    {
      name: "Crimson Water",
      alias: "Piranha",
      energy: "1",
      attack: "120",
      defense: "30",
      description: "Target injured enemy if this Axie's HP is below 50%.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-mouth-10.png",
    },
    {
      name: "Upstream Swim",
      alias: "Koi",
      energy: "1",
      attack: "110",
      defense: "30",
      description:
        "Apply Speed+ to this Axie for 2 rounds when comboed with another Aquatic class card.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-02.png",
    },
    {
      name: "Tail Slap",
      alias: "Nimo",
      energy: "1",
      attack: "20",
      defense: "0",
      description: "Gain 1 energy when comboed with another card.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-04.png",
    },
    {
      name: "Black Bubble",
      alias: "Tadpole",
      energy: "1",
      attack: "110",
      defense: "40",
      description: "Apply Jinx to target for 2 rounds.",
      attackType: "Ranged",
      class: "Aquatic",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-06.png",
    },
    {
      name: "Water Sphere",
      alias: "Ranchu",
      energy: "1",
      attack: "120",
      defense: "30",
      description: "Apply Chill to target for 2 rounds.",
      attackType: "Ranged",
      class: "Aquatic",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-08.png",
    },
    {
      name: "Flanking Smack",
      alias: "Navaga",
      energy: "1",
      attack: "100",
      defense: "40",
      description: "Deal 120% damage if this Axie attacks first.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-10.png",
    },
    {
      name: "Chitin Jump",
      alias: "Shrimp",
      energy: "1",
      attack: "30",
      defense: "30",
      description: "Prioritizes furthest target.",
      attackType: "Melee",
      class: "Aquatic",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-12.png",
    },
    {
      name: "Single Combat",
      alias: "Ronin",
      energy: "1",
      attack: "80",
      defense: "0",
      description:
        "Guaranteed critical strike when comboed with at least 2 other cards.",
      attackType: "Melee",
      class: "Beast",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-02.png",
    },
    {
      name: "Heroic Reward",
      alias: "Hero",
      energy: "1",
      attack: "60",
      defense: "0",
      description:
        "Draw a card when attacking an Aquatic, Bird, or Dawn target.",
      attackType: "Melee",
      class: "Beast",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-04.png",
    },
    {
      name: "Nitro Leap",
      alias: "Jaguar",
      energy: "1",
      attack: "120",
      defense: "35",
      description: "Always strike first if this Axie is in Last Stand.",
      attackType: "Melee",
      class: "Beast",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-06.png",
    },
    {
      name: "Revenge Arrow",
      alias: "Risky Beast",
      energy: "1",
      attack: "125",
      defense: "25",
      description: "Deal 150% damage if this Axie is in Last Stand.",
      attackType: "Melee",
      class: "Ranged",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-08.png",
    },
    {
      name: "Woodman Power",
      alias: "Timber",
      energy: "1",
      attack: "80",
      defense: "80",
      description:
        "Add Shield equal to the damage this cards deals to Plant targets.",
      attackType: "Melee",
      class: "Beast",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-10.png",
    },
    {
      name: "Juggling Balls",
      alias: "Furball",
      energy: "1",
      attack: "40",
      defense: "30",
      description: "Strike 3 times.",
      attackType: "Ranged",
      class: "Beast",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-12.png",
    },
    {
      name: "Branch Charge",
      alias: "Little Branch",
      energy: "1",
      attack: "125",
      defense: "25",
      description:
        "Increase crit chance by 20% if chained or comboed with a plant card.",
      attackType: "Melee",
      class: "Beast",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-02.png",
    },
    {
      name: "Ivory Stab",
      alias: "Ipm",
      energy: "1",
      attack: "80",
      defense: "30",
      description:
        "Gain 1 energy per critical strike dealt by your team this round.",
      attackType: "Melee",
      class: "Beast",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-04.png",
    },
    {
      name: "Merry Legion",
      alias: "Merry",
      energy: "1",
      attack: "75",
      defense: "85",
      description: "Add 20% shield to this Axie when played in a chain.",
      attackType: "Melee",
      class: "Beast",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-06.png",
    },
    {
      name: "Sugar Rush",
      alias: "Pocky",
      energy: "1",
      attack: "125",
      defense: "20",
      description: "Deal 10% additional damage for each allied Bug Axie.",
      attackType: "Melee",
      class: "Beast",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-08.png",
    },
    {
      name: "Sinister Strike",
      alias: "Dual Blade",
      energy: "1",
      attack: "130",
      defense: "30",
      description: "Deal 200% damage on critical strikes.",
      attackType: "Melee",
      class: "Beast",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-10.png",
    },
    {
      name: "Acrobatic",
      alias: "Arco",
      energy: "1",
      attack: "100",
      defense: "50",
      description: "Apply speed+ to this Axie for 2 rounds when attacking.",
      attackType: "Melee",
      class: "Beast",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-12.png",
    },
    {
      name: "Nut Crack",
      alias: "Nut Cracker",
      energy: "1",
      attack: "105",
      defense: "30",
      description:
        "Deal 120% damage when comboed with another 'Nut Cracker' card.",
      attackType: "Melee",
      class: "Beast",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-mouth-02.png",
    },
    {
      name: "Piercing Sound",
      alias: "Goda",
      energy: "1",
      attack: "80",
      defense: "40",
      description: "Destroy 1 of your opponent's energy.",
      attackType: "Ranged",
      class: "Beast",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-mouth-04.png",
    },
    {
      name: "Death Mark",
      alias: "Axie Kiss",
      energy: "1",
      attack: "100",
      defense: "30",
      description: "Apply Lethal to target if this Axie's HP is below 30%.",
      attackType: "Ranged",
      class: "Beast",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-mouth-08.png",
    },
    {
      name: "Self Rally",
      alias: "Confident",
      energy: "0",
      attack: "0",
      defense: "30",
      description: "Apply 2 Morale+ to this Axie for 2 rounds.",
      attackType: "Support",
      class: "Beast",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-mouth-10.png",
    },
    {
      name: "Luna Absorb",
      alias: "Cottontail",
      energy: "0",
      attack: "0",
      defense: "30",
      description: "Gain 1 energy.",
      attackType: "Ranged",
      class: "Beast",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-02.png",
    },
    {
      name: "Night Steal",
      alias: "Rice",
      energy: "1",
      attack: "80",
      defense: "10",
      description:
        "Steal 1 energy from your opponent when comboed with another card.",
      attackType: "Melee",
      class: "Beast",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-04.png",
    },
    {
      name: "Rampant Howl",
      alias: "Shiba",
      energy: "1",
      attack: "120",
      defense: "30",
      description:
        "Apply Morale+ to your team for 2 rounds if this Axie attacks while in Last Stand.",
      attackType: "Melee",
      class: "Beast",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-06.png",
    },
    {
      name: "Hare Dagger",
      alias: "Hare",
      energy: "1",
      attack: "120",
      defense: "30",
      description:
        "Draw a card if this Axie attacks at the beginning of the round.",
      attackType: "Ranged",
      class: "Beast",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-08.png",
    },
    {
      name: "Nut Throw",
      alias: "Nut Cracker",
      energy: "1",
      attack: "105",
      defense: "30",
      description:
        "Deal 120% damage when comboed with another 'Nut Cracker' card.",
      attackType: "Ranged",
      class: "Beast",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-10.png",
    },
    {
      name: "Gerbil Jump",
      alias: "Gerbil",
      energy: "1",
      attack: "40",
      defense: "20",
      description:
        "Skip the closest target if there are 2 or more enemies remaining.",
      attackType: "Melee",
      class: "Beast",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-12.png",
    },
    {
      name: "Early Bird",
      alias: "Swallow",
      energy: "1",
      attack: "110",
      defense: "20",
      description: "Deal 120% damage if this Axie attacks first.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-02.png",
    },
    {
      name: "Sunder Armor",
      alias: "Feather fan",
      energy: "1",
      attack: "40",
      defense: "90",
      description: "Add 20% shield to this Axie for each debuff it possesses.",
      attackType: "Melee",
      class: "Bird",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-04.png",
    },
    {
      name: "Risky feather",
      alias: "The last one",
      energy: "1",
      attack: "150",
      defense: "0",
      description: "Apply 2 Attack- to this Axie.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-06.png",
    },
    {
      name: "Puffy smack",
      alias: "Cloud",
      energy: "1",
      attack: "100",
      defense: "50",
      description: "Skip targets that are in Last Stand.",
      attackType: "Melee",
      class: "Bird",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-08.png",
    },
    {
      name: "Cool breeze",
      alias: "Granma's fan",
      energy: "1",
      attack: "120",
      defense: "30",
      description: "Apply Chill to target for 2 rounds.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-10.png",
    },
    {
      name: "All-out shot",
      alias: "Post fight",
      energy: "0",
      attack: "110",
      defense: "0",
      description: "Inflict 30% of this Axie's max HP to itself.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-12.png",
    },
    {
      name: "Balloon pop",
      alias: "Balloon",
      energy: "0",
      attack: "40",
      defense: "0",
      description:
        "Apply Fear to target for 1 turn. If defending, apply Fear to self until next round.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-02.png",
    },
    {
      name: "Heart break",
      alias: "Cupid",
      energy: "1",
      attack: "120",
      defense: "20",
      description: "Apply Morale- to enemy for 2 rounds.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-04.png",
    },
    {
      name: "Ill-omened",
      alias: "Raven",
      energy: "1",
      attack: "110",
      defense: "30",
      description: "Apply Morale- to enemy for 2 rounds.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-06.png",
    },
    {
      name: "Blackmail",
      alias: "Pigeon post",
      energy: "1",
      attack: "120",
      defense: "30",
      description: "Apply Morale- to enemy for 2 rounds.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-06.png",
    },
    {
      name: "Patient hunter",
      alias: "Kingfisher",
      energy: "1",
      attack: "130",
      defense: "0",
      description:
        "Target an Aquatic class enemy if this Axie's HP is below 50%.",
      attackType: "Melee",
      class: "Bird",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-10.png",
    },
    {
      name: "Triple threat",
      alias: "Tri feather",
      energy: "0",
      attack: "40",
      defense: "10",
      description: "Attack twice if this Axie has any debuffs.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-12.png",
    },
    {
      name: "Soothing song",
      alias: "Doubletalk",
      energy: "1",
      attack: "60",
      defense: "0",
      description: "Ignore shield. Apply sleep to target.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-mouth-02.png",
    },
    {
      name: "Peace treaty",
      alias: "Peace maker",
      energy: "1",
      attack: "120",
      defense: "30",
      description: "Apply Attack- on target.",
      attackType: "Melee",
      class: "Bird",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-mouth-04.png",
    },
    {
      name: "Insectivore",
      alias: "Hungry bird",
      energy: "1",
      attack: "110",
      defense: "40",
      description: "Target Bug class enemy if this Axie's HP is below 50%.",
      attackType: "Melee",
      class: "Bird",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-mouth-08.png",
    },
    {
      name: "Dark swoop",
      alias: "Little owl",
      energy: "1",
      attack: "25",
      defense: "0",
      description: "Target fastest enemy.",
      attackType: "Melee",
      class: "Bird",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-mouth-10.png",
    },
    {
      name: "Eggbomb",
      alias: "Eggshell",
      energy: "1",
      attack: "120",
      defense: "0",
      description: "Apply Aroma on this Axie until next round.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-02.png",
    },
    {
      name: "Cockadoodledoo",
      alias: "Cuckoo",
      energy: "0",
      attack: "0",
      defense: "30",
      description: "Apply Attack+ to this Axie.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-04.png",
    },
    {
      name: "Air force one",
      alias: "Trump",
      energy: "1",
      attack: "120",
      defense: "30",
      description: 'Deal 120% damage when chained with another "Trump" card.',
      attackType: "Melee",
      class: "Bird",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-06.png",
    },
    {
      name: "Headshot",
      alias: "Kestrel",
      energy: "1",
      attack: "130",
      defense: "0",
      description: "Disable target's horn cards next round.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-08.png",
    },
    {
      name: "Smart shot",
      alias: "Wing horn",
      energy: "1",
      attack: "50",
      defense: "10",
      description:
        "Skip the closest target if there are 2 or more enemies remaining.",
      attackType: "Ranged",
      class: "Bird",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-10.png",
    },
    {
      name: "Feather lunge",
      alias: "Feather spear",
      energy: "1",
      attack: "110",
      defense: "50",
      description: 'Deal 120% damage when chained with another "Lunge" card.',
      attackType: "Melee",
      class: "Bird",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-12.png",
    },
    {
      name: "Turnip Rocket",
      alias: "Turnip",
      energy: "1",
      attack: "60",
      defense: "80",
      description: "Target a bird if comboed with 2 or more cards.",
      attackType: "Ranged",
      class: "Plant",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-02.png",
    },
    {
      name: "Shroom's Grace",
      alias: "Shiitake",
      energy: "1",
      attack: "0",
      defense: "84",
      description: "Heal this Axie for 120 HP.",
      attackType: "Support",
      class: "Plant",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-04.png",
    },
    {
      name: "Cleanse Scent",
      alias: "Bidens",
      energy: "0",
      attack: "0",
      defense: "50",
      description: "Remove all debuffs from this Axie.",
      attackType: "Support",
      class: "Plant",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-06.png",
    },
    {
      name: "Aqua Stock",
      alias: "Watering Can",
      energy: "1",
      attack: "45",
      defense: "80",
      description: "Gain 1 energy if this Axie is struck by an Aquatic card.",
      attackType: "Ranged",
      class: "Plant",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-08.png",
    },
    {
      name: "Refresh",
      alias: "Mint",
      energy: "0",
      attack: "0",
      defense: "50",
      description:
        "Remove all debuffs from a teammate if its directly in front (same row) of this Axie.",
      attackType: "Support",
      class: "Plant",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-10.png",
    },
    {
      name: "October Treat",
      alias: "Pumpkin",
      energy: "1",
      attack: "1",
      defense: "110",
      description:
        "Draw a card if this Axie's shield doesn't break this round.",
      attackType: "Melee",
      class: "Plant",
      partType: "Back",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-12.png",
    },
    {
      name: "Bamboo Clan",
      alias: "Bamboo Shoot",
      energy: "1",
      attack: "80",
      defense: "70",
      description: "Increased 20% damage when chained with another plant card.",
      attackType: "Melee",
      class: "Plant",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-02.png",
    },
    {
      name: "Wooden Stab",
      alias: "Beech",
      energy: "1",
      attack: "105",
      defense: "40",
      description: "Deal 120% damage if this Axie's shield breaks.",
      attackType: "Melee",
      class: "Plant",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-04.png",
    },
    {
      name: "Healing Aroma",
      alias: "Rose Bud",
      energy: "1",
      attack: "0",
      defense: "50",
      description: "Heal this Axie for 120 HP.",
      attackType: "Support",
      class: "Plant",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-06.png",
    },
    {
      name: "Sweet Party",
      alias: "Strawberry Shortcake",
      energy: "2",
      attack: "0",
      defense: "40",
      description:
        "Heal front teammate for 270 HP. If there are no front teammates, heal this Axie instead.",
      attackType: "Support",
      class: "Plant",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-08.png",
    },
    {
      name: "Prickly Trap",
      alias: "Cactus",
      energy: "1",
      attack: "115",
      defense: "20",
      description: "Deal 120% damage if this Axie attacks last.",
      attackType: "Melee",
      class: "Plant",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-10.png",
    },
    {
      name: "Seed Bullet",
      alias: "Watermelon",
      energy: "1",
      attack: "30",
      defense: "50",
      description: "Target the fastest enemy.",
      attackType: "Ranged",
      class: "Plant",
      partType: "Horn",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-12.png",
    },
    {
      name: "Vegetal Bite",
      alias: "Serious",
      energy: "1",
      attack: "30",
      defense: "30",
      description:
        "Steal 1 energy from your opponent when comboed with another card.",
      attackType: "Melee",
      class: "Plant",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-mouth-02.png",
    },
    {
      name: "Drain Bite",
      alias: "Zigzag",
      energy: "1",
      attack: "60",
      defense: "60",
      description: "Heal this Axie by the damage this card inflicts.",
      attackType: "Melee",
      class: "Plant",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-mouth-04.png",
    },
    {
      name: "Vegan Diet",
      alias: "Herbivore",
      energy: "1",
      attack: "75",
      defense: "75",
      description:
        "Heal this Axie by the damage this card inflicts on a Plant target.",
      attackType: "Melee",
      class: "Plant",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-mouth-08.png",
    },
    {
      name: "Forest Spirit",
      alias: "Silence Whisper",
      energy: "1",
      attack: "0",
      defense: "40",
      description: "Heal front teammate for 190 HP.",
      attackType: "Support",
      class: "Plant",
      partType: "Mouth",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-mouth-10.png",
    },
    {
      name: "Carrot Hammer",
      alias: "Carrot",
      energy: "1",
      attack: "70",
      defense: "40",
      description:
        "Gain 1 energy if this Axie's shield breaks. Can only trigger once per round.",
      attackType: "Melee",
      class: "Plant",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-02.png",
    },
    {
      name: "Cattail Slap",
      alias: "Cattail",
      energy: "0",
      attack: "20",
      defense: "30",
      description: "Draw a card if struck by a Beast, Bug, or Mech card.",
      attackType: "Melee",
      class: "Plant",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-04.png",
    },
    {
      name: "Leek Leak",
      alias: "Hatsune",
      energy: "1",
      attack: "60",
      defense: "80",
      description: "When hit, disable the attacker's ranged cards next round.",
      attackType: "Melee",
      class: "Plant",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-06.png",
    },
    {
      name: "Aqua Deflect",
      alias: "Potato Leaf",
      energy: "1",
      attack: "70",
      defense: "80",
      description:
        "Cannot be targeted by Aquatic cards if this Axie has teammates remaining.",
      attackType: "Melee",
      class: "Plant",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-10.png",
    },
    {
      name: "Spicy Surprise",
      alias: "Hot Butt",
      energy: "1",
      attack: "90",
      defense: "50",
      description: "Disable target's mouth cards next round.",
      attackType: "Melee",
      class: "Plant",
      partType: "Tail",
      imgUrl:
        "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-12.png",
    },
  ],
};

export { axieCards };
